### ISSUE TITLE
Tabs needs to changes while generating API Key.

### ISSUE THREAD

**Issue by hempun10** [outerbase/outerbase#24]
**Describe the bug**
When we try to generate an API key, the API key does appear as the toast shows. We need to change the tabs to see the API. 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'General'
3. Click on 'Generate API'
4. See Error

**Expected behavior**
When we click on the 'GENERATE API " button it should show toast and API key simultaneously.

**Screenshots**
<img width="959" alt="image" src="https://github.com/Outerbase/outerbase/assets/106392313/a776b20b-3a78-436a-9044-3e947ad60655">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: v1.57.62

**Comment by Brayden** [comment]
Thanks for reporting this @hempun10. Logging this internally for developer prioritization!
