### ISSUE TITLE
Dark mode not saved when refreshing the page

### ISSUE THREAD

**Issue by Mihan786Chistie** [Outerbase/outerbase#6]
**Describe the bug**
On the Outerbase website home page, there is a recurring problem where the Dark Mode setting is not retained when users refresh the page. The current website implementation fails to remember the user's choice, causing an inconvenience each time the page is refreshed.

**To Reproduce**
1. Go to https://outerbase.com/
2. Scroll down to dark mode/light mode toggle
3. Toggle the switch to Dark mode
4. Refresh the page
5. Switch toggled back to light mode

**Expected behavior**
When a user switches to Dark Mode, their choice should be saved and remembered across sessions and page refreshes. This means that if a user enables Dark Mode once, it should remain enabled until the user chooses to disable it.

**Screenshots**
![darkMode_Outerbase](https://github.com/Outerbase/outerbase/assets/42113027/dde7122e-99f8-48bb-b407-c37b2613131d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 116.0.5845.111

**Comment by stritt** [comment]
Hey thanks for the feedback @Mihan786Chistie we've since updated the site to fix this. Also, this isn't a toggle to update the whole site, but a toggle to show the different states of the video. We will rework the UX here to better reflect that!
