### ISSUE TITLE
Add placeholders or labels for inputs in commands

### ISSUE THREAD

**Issue by fadkeabhi** [Outerbase/outerbase#7]
### Description of the desired feature : 
Its my request to add the placeholders for the input fields. What values are expected there.
![image](https://github.com/Outerbase/outerbase/assets/31249309/b80a0047-61a6-467e-8073-17b4b4b966ca)

### Use cases for the feature: 
It will make it easy to understand.

### Why the feature is valuable for the project: 
Personally speaking it took me an hour to figure out the expected values are {variable name} and {default value}. It may be the case for majority.

### The end result may look like
![image](https://github.com/Outerbase/outerbase/assets/31249309/546ac6bb-c3d7-4bf7-9022-138301ae71f7)

**Comment by Brayden** [comment]
@fadkeabhi Thanks for bringing this issue to our attention. You should now see this change deployed and resolved. Closing the issue now!

**Comment by fadkeabhi** [comment]
Wow, that was a fast fix! Thanks, @Brayden , for addressing this issue so quickly. The placeholders and labels make things much clearer. Great job!

**Comment by Brayden** [comment]
Agreed! Your recommendation was a great one :)
